### ISSUE TITLE
Problème création n8nio

### ISSUE THREAD

**Issue by Bono2007** [projetssd/kubeseed#58]
Le bug qui existait sous ssdv2 mais qui a été résolu par un patch, le patch ici dépasse mes compétences et je manque de temps.
Voilà ce que j'ai fait : 
app_persos/n8nio.yml : 
```
---
application: 'n8nio'
app_port: 5678
description: "n8n is a free and source-available workflow automation tool"
image: 'n8nio/n8n'
application_volumes:
  - local_path: "{{ lookup('env', 'APP_SETTINGS') }}/{{application}}/config"
    container_path: "/home/node/.n8n"

application_env:
  - name: DB_TYPE
    value: "postgresdb"
  - name: DB_POSTGRESDB_DATABASE
    value: "{{ application }}"
  - name: DB_POSTGRESDB_HOST
    value: "db-{{ application }}"
  - name: DB_POSTGRESDB_PORT
    value: "5432"
  - name: DB_POSTGRESDB_PASSWORD
    value: "{{ application }}"
  - name: TZ
    value: "Europe/Paris"
  - name: WEBHOOK_URL
    value: "https://{{ applis[application].subdomain }}.{{ user.domain }}"
  - name: N8N_LOG_LEVEL
    value : "debug"
  - name: N8N_BASIC_AUTH_ACTIVE
    value : "true"
  - name: N8N_BASIC_AUTH_USER
    value : "{{ user.name }}"
  - name: N8N_BASIC_AUTH_PASSWORD
    value : "{{ user.pass }}"
pretasks:
  - postgresqldb
```
Ajout de la task postgresqldb avec modification de dbimage: "postgresdb"
```
---
- name: Set facts
  set_fact:
    dbimage: "postgresdb"
    db_app_port: 5432
    db_persistent_path: "/var/lib/postgresql/data"
    db_application_env:
      - name: "POSTGRES_DB"
        value: "{{ application }}"
      - name: "POSTGRES_USER"
        value: "{{ application }}"
      - name: "POSTGRES_PASSWORD"
        value: "{{ application }}"

- name: Launch databasess
  include_tasks: "{{ settings.source }}/containers/tasks/bdd.yml"
```
Il faudrait une posttask dans ce genre : 
```
metadata:
  name: chown-job
spec:
  template:
    spec:
      containers:
      - name: chown-container
        image: n8nio/base:16
        command: ["chown", "-R", "node:node", "/home/node/.n8n"]
        volumeMounts:
        - name: n8n-settings
          mountPath: /home/node/.n8n
      restartPolicy: Never
      volumes:
      - name: n8n-settings
        hostPath:
          path: ${SETTINGS_STORAGE}/node/.n8n
```
